drop schema if exists onewaydb;
create schema onewaydb;
use onewaydb;

-- if tables exist do not create them
drop table if exists CUSTOMERS;
drop table if exists FLIGHTS;
drop table if exists SEATS;
drop table if exists ORDERS;

CREATE TABLE CUSTOMERS (
	CUST_ID VARCHAR(4),
    FNAME VARCHAR(25) NOT NULL,
    LNAME VARCHAR(25) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL,
    PWD VARCHAR(20) NOT NULL,
    PRIMARY KEY (CUST_ID)
);

CREATE TABLE FLIGHTS (
	FLIGHT_ID VARCHAR(4),
    PLANE_MODEL varchar(10),
    AIRLINE VARCHAR(3),
    FLIGHT_NUM VARCHAR(4) NOT NULL,
    DEPART_LOC VARCHAR(3) NOT NULL,
    LAND_LOC VARCHAR(3) NOT NULL,
    DEPART_TIME DATETIME NOT NULL,
    LAND_TIME DATETIME NOT NULL,
	PRIMARY KEY (FLIGHT_ID)
);


CREATE TABLE SEATS (
	SEAT_ID VARCHAR(4),
    SEAT_NUM VARCHAR(4) NOT NULL,
    FLIGHT_ID VARCHAR(4) NOT NULL,
    E_AVAILABILITY MEDIUMINT(3) NOT NULL,
    B_AVAILABILITY MEDIUMINT(3) NOT NULL, 
    FC_AVAILABILITY MEDIUMINT(3) NOT NULL, 
    E_PRICE DECIMAL(6,2) NOT NULL,
    B_PRICE DECIMAL(6,2) NOT NULL,
    FC_PRICE DECIMAL(6,2) NOT NULL, 
	PRIMARY KEY (SEAT_ID),
    FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHTS(FLIGHT_ID)
);

CREATE TABLE ORDERS (
	ORDER_ID VARCHAR(4), 
    CUST_ID VARCHAR(4) NOT NULL,
    FLIGHT_ID VARCHAR(4) NOT NULL,
    PRICE DECIMAL(6,2),
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (CUST_ID) REFERENCES CUSTOMERS(CUST_ID),
    FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHTS(FLIGHT_ID)
);